config/routes.rb
Angelhack::Application.routes.draw do
  resources :surveys

  resources :questions

  resources :votes
  resources :comments
  resources :categories

  resources :venues do
    resources :reports
  end

  resources :reports do
    resources :votes
  end

  devise_for :users, :token_authentication_key => 'authentication_key'

=begin
  resource :session do
    collection do
      get 'callback'
    end
  end
=end

  root to: 'home#index'

end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  report_id  :string(255)
#  resp_id    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Survey < ActiveRecord::Base
  belongs_to :report
  belongs_to :response
  
  attr_accessible :report_id, :response_id
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.haml
= form_for @survey do |f|
  - if @survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @survey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :report
    = f.text_field :report
  .field
    = f.label :response
    = f.text_field :response
  .actions
    = f.submit 'Save'

app/views/surveys/edit.html.haml
%h1 Editing survey

= render 'form'

= link_to 'Show', @survey
\|
= link_to 'Back', surveys_path

app/views/surveys/index.html.haml
%h1 Listing surveys

%table
  %tr
    %th Report
    %th Response
    %th
    %th
    %th

  - @surveys.each do |survey|
    %tr
      %td= survey.report
      %td= survey.response
      %td= link_to 'Show', survey
      %td= link_to 'Edit', edit_survey_path(survey)
      %td= link_to 'Destroy', survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Survey', new_survey_path

app/views/surveys/new.html.haml
%h1 New survey

= render 'form'

= link_to 'Back', surveys_path

app/views/surveys/show.html.haml
%p#notice= notice

%p
  %b Report:
  = @survey.report
%p
  %b Response:
  = @survey.response

= link_to 'Edit', edit_survey_path(@survey)
\|
= link_to 'Back', surveys_path