config/routes.rb
Angelhack::Application.routes.draw do
  resources :surveys

  resources :questions

  resources :votes
  resources :comments
  resources :categories

  resources :venues do
    resources :reports
  end

  resources :reports do
    resources :votes
  end

  devise_for :users, :token_authentication_key => 'authentication_key'

=begin
  resource :session do
    collection do
      get 'callback'
    end
  end
=end

  root to: 'home#index'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  content    :string(255)
#  latitude   :float
#  longitude  :float
#  gmaps      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  state      :string(255)      default("1")
#  user_id    :integer          not null
#  venue_id   :integer          not null
#

class Report < ActiveRecord::Base
  attr_accessible :content, :state, :user_id, :venue_id, :name

  belongs_to :user
  belongs_to :venue, touch: true
  has_many :votes
  has_many :comments
  has_many :surveys

  validates :venue_id, presence: true
  validates :user_id, presence: true

  STATES = {
    0 => :pendiente,
    1 => :en_revision,
    2 => :recompensado,
    3 => :spam,
    4 => :revisado
  }

  def positive_votes
    self.votes.where(calification: true).size
  end

  def negative_votes
    self.votes.where(calification: false).size
  end
    
  state_machine :state, initial: :pendiente do

   	STATES.each do |value,name|
        state name, value: value
    end

  	event :review do
  		transition :pendiente => :revisado
  	end

  	event :not_review do
  		transition :revisado => :pendiente
  	end

  	event :in_review do
  		transition :pendiente => :en_revision
  	end

  	event :reward do
  		transition :revisado => :recomensado
  	end

  	event :spamed do
  		transition any => :spam
  	end

  	event :not_spamed do
  		transition :spam => :pendiente
  	end

  	state :revisado
  	state :pendiente
  	state :en_revision
  	state :recomensado
  	state :spam

  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  skip_authorization_check :only => [:index, :show]
  
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report

    if params[:venue_id].present?
      @reports = @reports.where(venue_id: params[:venue_id])
    elsif current_user.present?
      @reports = @reports.where(user_id: current_user.id)
    else
      @reports = @reports.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports, only: [:id,:content,:name,:state,:created_at, :user_id], include: {
          comments: { only: [:id, :description] }
        },
        methods: [:positive_votes, :negative_votes]
      }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report].merge(user_id: current_user.id, venue_id: params[:venue_id]))

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_field :content
  / .field
  /   = f.label :latitude
  /   = f.text_field :latitude
  / .field
  /   = f.label :longitude
  /   = f.text_field :longitude
  / .field
  /   = f.label :gmaps
  /   = f.check_box :gmaps
  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
%h1 Listing reports

%table
  %tr
    %th Name
    %th Content
    %th Latitude
    %th Longitude
    %th Gmaps
    %th State
    %th
    %th
    %th

  - @reports.each do |report|
    %tr
      %td= report.name
      %td= report.content
      %td= report.latitude
      %td= report.longitude
      %td= report.gmaps
      %td= report.state 
      - if can? :destroy, Report
        %td= link_to 'Show', report
        %td= link_to 'Edit', edit_report_path(report)
        %td= link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Report', new_report_path

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @report.name
%p
  %b Content:
  = @report.content
/ %p
/   %b Latitude:
/   = @report.latitude
/ %p
/   %b Longitude:
/   = @report.longitude
/ %p
/   %b Gmaps:
/   = @report.gmaps

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path